name: Automatic Rebase
on:
  push:
    branches-ignore:
      # Ignore branches automatically created by github-rebase
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**
  pull_request_target:
    types:
      - labeled
jobs:
  auto-rebase:
    name: AutoRebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2.0.2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: Label305/AutoRebase@v0.1
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
